# SQLite. Versions 3.8.0 and up are supported.
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem "sqlite3"
#
default: &default
  pool: 5
  timeout: 5000

development:
  adapter: postgresql
  database: panga_portal_development

test:
  adapter: postgresql
  database: panga_portal_test

production:
  adapter: postgresql
  database: panga_portal_production
